modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/LukeGrahamLandryMC/tieredshulkers/issues"
license="GNU General Public License v3.0"

[[mods]]
    modId="tieredshulkers"
    namespace="tieredshulkers"
    version="${version}"
    displayName="Tiered Shulkers"
    authors="LukeGrahamLandry#6888"
    credits="Originally Iron Shulker Boxes (by cpw, alexbegt, progwml6)"
    description='''
New Shulker Boxes with larger sizes, with in-place upgrade items.
    '''
    displayURL="https://www.curseforge.com/minecraft/mc-mods/tiered-shulkers"
    [[dependencies.tieredshulkers]]
        modId="forge"
        mandatory=true
        versionRange="[41,)"
        ordering="NONE"
        side="BOTH"
