modLoader="javafml"
loaderVersion="[${javafml_min},${javafml_max})"
issueTrackerURL="https://github.com/LukeGrahamLandryMC/tieredshulkers/issues"
license="GNU General Public License v3.0"

[[mods]]
    modId="tieredshulkers"
    namespace="tieredshulkers"
    version="${version}"
    displayName="Tiered Shulkers"
    authors="LukeGrahamLandry#6888"
    credits="Originally Iron Shulker Boxes (by cpw, alexbegt, progwml6)"
    description='''
New Shulker Boxes with larger sizes, with in-place upgrade items.
    '''
    displayURL="https://github.com/LukeGrahamLandryMC/tieredshulkers"
    [[dependencies.tieredshulkers]]
        modId="forge"
        mandatory=true
        versionRange="[${forge_version_min},${forge_version_max})"
        ordering="NONE"
        side="BOTH"
